### ISSUE TITLE
What is the license ?

### ISSUE THREAD

**Issue by ayourtch** [pachev/pachev_ftp#1]
I looked at the code and might use it in one of my projects to replace an existing component (experimenting with moving from C# to rust :-) - but there is no license file in the project, so it is a bit unclear... could you please add it to the repo ? Thanks a lot!

**Comment by pachev** [comment]
Hi, been away for quite some time. You're free to use it. I'll update right now

**Comment by ayourtch** [comment]
Thanks a lot!!
