### ISSUE TITLE
There is only 200 subsequent client connections possible...

### ISSUE THREAD

**Issue by ayourtch** [pachev/pachev_ftp#2]
Hi, thanks a lot for the nice and easy to follow code!

I noticed that as the clients connect and disconnect, the client counter keeps increasing. So, after 200 connects, the server needs to be restarted. So I came up with this (somewhat clunky, needing cleanup probably) way of reclaiming the resources - thus now your server can support 200 *simultaneous* clients.

If you think it is worth it as is, I can open a pull request - but I decided to let you to look at it first :)

https://github.com/ayourtch/pachev_ftp/commit/0d2bd7391dd2627eef9a9998467a6ece4c70de0b

**Comment by pachev** [comment]
Hi, 

Yes please submit a PR. To be honest, I wrote this code while learning rust. It's not completely optimized. Any optimizations a greatly welcome. Also, thanks for using the code. How's your rust experience so far?

**Comment by ayourtch** [comment]
Ok, just did! Yeah there are a few small rough edges, but works perfectly well for my purposes so far!

 I am learning rust by rewriting a bunch of small backend components in a home-grown NMS system (and borrowing some others like your FTP), it’s really fun to see the memory usage so much lower and rock solid compared to C# mono :) I had a little bit of trouble getting my head around using ssh library, but that was a very valuable experience in terms of learning. And the community is excellent. Once I get a bit more confident - I will try to make my rust plugin for FD.io VPP actually forward packets and see how it fares compared to C! Coding with Rust is so pleasant and fun !  And very nice community too! Looking forward to FOSDEM in February!

**Comment by pachev** [comment]
Thanks for the contribution! I'm glad you're having a nice time learning rust. I need to start writing some more rust code. Really busy with work though at the moment. Hoping to find some time soon. Wish I could go to FOSDEM, haven't been to Belgium in years.
